-- DROP LIKES TABLE.
DROP TABLE IF EXISTS likes;

-- DROP FOLLOWS TABLE.
DROP TABLE IF EXISTS follows;

-- DROP POSTS TABLE.
DROP TABLE IF EXISTS posts;

-- DROP USERS TABLE.
DROP TABLE IF EXISTS users;